guarantee:
  nosql:
    enabled: false
  sql:
    enabled: false
  kafka:
    enabled: false
http1:
  url: http://localhost:8081/test
  headersMap:
    Accept: "application/json"
  retryConfiguration:
    exceptionsMap:
      org.springframework.web.client.HttpServerErrorException: true
    maxAttempts: 3
    initialInterval: 5
    intervalMultiplier: 5
    maxInterval: 100
http2:
  url: http://localhost:8081/test/2
  headersMap:
    Accept: "application/json"
  retryConfiguration:
    exceptionsMap:
      org.springframework.web.client.HttpServerErrorException: true
    maxAttempts: 3
    initialInterval: 5
    intervalMultiplier: 5
    maxInterval: 100