guarantee:
  nosql:
    enabled: false
  sql:
    enabled: true
    sender:
      properties-map:
        db1:
          url: jdbc:postgresql://localhost:5432/db1
          user-name: user
          password: 1234
          driver-class-name: org.postgresql.Driver
    puller:
      limit: 5
      #cron: "0 15 10 * * ?"
      cron: "*/30 * * * * ?"
    cleaner:
      limit: 5
      #cron: "*/10 * * * * ?"
      cron: "0 15 10 * * ?"
  kafka:
    enabled: false
http1:
  url: http://localhost:8081/test
  headersMap:
    Accept: "application/json"
  retryConfiguration:
    exceptionsMap:
      org.springframework.web.client.HttpServerErrorException: true
    maxAttempts: 3
    initialInterval: 5
    intervalMultiplier: 5
    maxInterval: 100
http2:
  url: http://localhost:8081/test/2
  headersMap:
    Accept: "application/json"
  retryConfiguration:
    exceptionsMap:
      org.springframework.web.client.HttpServerErrorException: true
    maxAttempts: 3
    initialInterval: 5
    intervalMultiplier: 5
    maxInterval: 100